services:
  thesis-static:
    image: nginx:alpine
    container_name: thesis-static
    restart: unless-stopped
    volumes:
      - ./test:/usr/share/nginx/html:ro
    networks:
      - webnet

networks:
  webnet:
    external: true